version: '3.9'

services:
   # Frontend
   app:
      container_name: DS1_Frontend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./ProjectBlackBird_Frontend
         dockerfile: Dockerfile
      env_file:
         - ./ProjectBlackBird_Frontend/.env
      volumes:
         - './ProjectBlackBird_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always

   # Backend
   api:
      container_name: DS1_Backend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./ProjectBlackBird_Backend
         dockerfile: Dockerfile
      ports:
         - '8000:8000'
      env_file:
         - ./ProjectBlackBird_Backend/.env
      volumes:
         - /app/node_modules
         - ./ProjectBlackBird_Backend:/app
         - ./Nginx/Server_ssl/192.168.12.209.crt:/app/ssl/192.168.12.209.crt
         - ./Nginx/Server_ssl/192.168.12.209.key:/app/ssl/192.168.12.209.key
      restart: always

   # Server
   server:
      container_name: DS1_Server
      environment:
         - TZ=America/Phoenix
      image: nginx
      depends_on:
         - api
         - app
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - ./Nginx/Server_ssl/192.168.12.209.crt:/etc/nginx/192.168.12.209.crt
         - ./Nginx/Server_ssl/192.168.12.209.key:/etc/nginx/192.168.12.209.key
      restart: always
