--
-- Name: jobdefinition; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.jobdefinition;

CREATE TABLE public.jobdefinition (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description character varying(100),
    defaulttargetprice double precision,
    hourstocomplete double precision,
    billable boolean
);

--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.company;

CREATE TABLE public.company (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phantompayment double precision NULL,
    newbalance BOOLEAN DEFAULT FALSE,
    balancechanged BOOLEAN DEFAULT FALSE,
    companyname TEXT NULL,
    firstname TEXT NULL,
    lastname TEXT NULL,
    middlei TEXT NULL,
    address1 TEXT NULL,
    address2 TEXT NULL,
    address3 TEXT NULL,
    city TEXT NULL,
    state TEXT NULL,
    zip TEXT NULL,
    country TEXT NULL,
    phonenumber1 TEXT NULL,
    phonenumber2 TEXT NULL,
    mobilephone TEXT NULL,
    fax TEXT NULL,
    email TEXT NULL,
    url TEXT NULL,
    outlookid TEXT NULL,
    currentbalance double precision NULL,
    beginningbalance double precision NULL,
    statementbalance double precision NULL,
    other double precision NULL,
    inactive BOOLEAN DEFAULT TRUE,
    note TEXT NULL,
    originalcurrentbalance double precision NULL,
    usertag TEXT NULL,
    ageingadjustment double precision NULL,
    notbillable BOOLEAN DEFAULT FALSE,
    agingcorrection double precision NULL
);

--
-- Name: invoice; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.invoice;

CREATE TABLE public.invoice (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company INTEGER REFERENCES public.company(OID),
    invoicenumber character varying(100),
    contactname character varying(100),
    address1 character varying(100),
    address2 character varying(100),
    address3 character varying(100),
    address4 character varying(100),
    address5 character varying(100),
    address6 character varying(100),
    beginningbalance double precision,
    totalpayments double precision,
    totalnewcharges double precision,
    endingbalance double precision,
    unpaidbalance double precision,
    invoicedate timestamp without time zone,
    paymentduedate timestamp without time zone,
    dataenddate timestamp without time zone
);

--
-- Name: invoicedetail; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.invoicedetail;

CREATE TABLE public.invoicedetail (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    invoice INTEGER,
    detaildate timestamp without time zone,
    detailtype character varying(100),
    jobdescription character varying(100),
    charges double precision,
    discount double precision,
    writeoff double precision,
    net double precision,
    payment double precision,
    rawcharges double precision
);

--
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.employee;

CREATE TABLE public.employee (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname character varying(100),
    lastname character varying(100),
    middlei character varying(100),
    ssn character varying(100),
    employeenumber character varying(100),
    address1 character varying(100),
    address2 character varying(100),
    city character varying(100),
    state character varying(100),
    zip character varying(100),
    homephone character varying(100),
    mobilephone character varying(100),
    workphone character varying(100),
    pager character varying(100),
    fax character varying(100),
    otherphone character varying(100),
    contact character varying(100),
    startdate timestamp without time zone,
    availabledate timestamp without time zone,
    hourlycost double precision,
    inactive boolean,
    note character varying(100),
    passwrd character varying(100),
    usertype character varying(100),
    username character varying(100)
);

--
-- Name: job; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.job;

CREATE TABLE public.job (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jobdefinition INTEGER,
    company INTEGER REFERENCES public.company(OID),
    targetprice double precision,
    defaulttargetprice double precision,
    scheduleddate timestamp without time zone,
    startdate timestamp without time zone,
    actualdate timestamp without time zone,
    contact character varying(100),
    contactphone character varying(100),
    contactemail character varying(100),
    description character varying(100),
    defaultdescription character varying(100),
    percentcomplete double precision,
    discount double precision,
    hourstocomplete double precision,
    iscomplete boolean
);

--
-- Name: setupdata; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.setupdata;

CREATE TABLE public.setupdata (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customername character varying(100),
    customeraddress character varying(100),
    customercity character varying(100),
    customerstate character varying(100),
    customerzip character varying(100),
    customerphone character varying(100),
    customerfax character varying(100),
    dayofweek integer,
    calendarweekrule integer,
    lastinvoicenumber integer,
    lockedby character varying(100),
    statementtext character varying(100)
);

--
-- Name: transaction; Type: TABLE; Schema: public; Owner: -
--
DROP TABLE IF EXISTS public.transaction;

CREATE TABLE public.transaction (
    OID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company INTEGER NOT NULL,
    job INTEGER NOT NULL,
    employee INTEGER NOT NULL,
    transactiontype character varying(100) NULL,
    transactiondate timestamp without time zone NULL,
    quantity double precision NULL,
    unitofmeasure character varying(100) NULL,
    unittransaction double precision NULL,
    totaltransaction double precision NULL,
    starttime timestamp without time zone NULL,
    endtime timestamp without time zone NULL,
    reference character varying(100) NULL,
    noteordescription character varying(10485760) NULL,
    discount double precision NULL,
    invoice  INTEGER DEFAULT NULL,
    usertag character varying(100) NULL,
    paymentapplied boolean NULL,
    ignoreinageing boolean NULL
);
